project:
  type: website
  output-dir: _site
  
website:
  title: "Penguin DevOps Lab"
  navbar:
    left:
      - href: eda.qmd
        text: EDA
      - href: model.qmd
        text: Model Building

format:
  html:
    theme: cosmo
    toc: true

editor: visual

