# Generated by the vetiver package; edit with care

FROM rocker/r-ver:4.5.2
ENV RENV_CONFIG_REPOS_OVERRIDE=https://packagemanager.rstudio.com/cran/latest

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  cmake \
  libcurl4-openssl-dev \
  libicu-dev \
  libsodium-dev \
  libssl-dev \
  libuv1-dev \
  libx11-dev \
  libxml2-dev \
  make \
  zlib1g-dev \
  && apt-get clean
  
# OPTIMIZED: Replaced the massive 'paws' package with lightweight 'aws.s3'
RUN Rscript -e "install.packages(c('plumber', 'pins', 'vetiver', 'aws.s3', 'duckdb'), repos='https://packagemanager.posit.co/cran/__linux__/jammy/latest')"

COPY plumber.R /opt/ml/plumber.R
EXPOSE 46261
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('/opt/ml/plumber.R'); pr$run(host = '0.0.0.0', port = 46261)"]