# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "~/data/model")
v <- vetiver_pin_read(b, "penguins_model", version = "20260415T174753Z-82491")

#* @plumber
function(pr) {
    pr |> vetiver_api(v)
}
