# Generated by the vetiver package; edit with care
library(plumber)
library(pins)
library(vetiver)
library(paws) # Essential for S3 communication

# 1. Connect to your live S3 board
model_board <- board_s3(
  bucket = "do4ds-lab-sa", 
  region = "us-east-2"
)

# 2. Read the model pin directly from S3
v <- vetiver_pin_read(model_board, "penguins_model")

# 3. Create the Plumber API router and save it to the special object 'pr'
#* @apiTitle Penguins Model API
#* @apiDescription Predicting penguin body mass from S3 cloud artifacts
#* @plumber
function(pr) {
  vetiver_api(pr, v)
}